import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#191f31",
        "surface-variant": "#2e3447",
        "on-tertiary-container": "#3d455a",
        "on-surface-variant": "#d0c5af",
        "surface-dim": "#0c1324",
        "error-container": "#93000a",
        "surface-bright": "#33394c",
        "on-primary": "#3c2f00",
        "on-background": "#dce1fb",
        "secondary-fixed-dim": "#95d3ba",
        "surface-container-high": "#23293c",
        "on-surface": "#dce1fb",
        "surface-container-lowest": "#070d1f",
        "primary": "#f2ca50",
        "secondary": "#95d3ba",
        "secondary-container": "#0b513d",
        "on-secondary-fixed": "#002117",
        "primary-fixed-dim": "#e9c349",
        "on-error-container": "#ffdad6",
        "surface": "#0c1324",
        "on-primary-fixed-variant": "#574500",
        "inverse-on-surface": "#2a3043",
        "surface-container-low": "#151b2d",
        "tertiary": "#c6cee8",
        "on-error": "#690005",
        "surface-tint": "#e9c349",
        "tertiary-fixed-dim": "#bec6e0",
        "outline": "#99907c",
        "inverse-surface": "#dce1fb",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465c",
        "background": "#0c1324",
        "surface-container-highest": "#2e3447",
        "inverse-primary": "#735c00",
        "on-primary-container": "#554300",
        "on-tertiary": "#283044",
        "on-primary-fixed": "#241a00",
        "primary-container": "#d4af37",
        "outline-variant": "#4d4635",
        "tertiary-container": "#abb2cc",
        "on-secondary-container": "#83c2a9",
        "error": "#ffb4ab",
        "secondary-fixed": "#b0f0d6",
        "on-secondary": "#003829",
        "primary-fixed": "#ffe088",
        "on-secondary-fixed-variant": "#0b513d",
        "tertiary-fixed": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-xl": "64px",
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-md": ["var(--font-bodoni-moda)"],
        "headline-lg-mobile": ["var(--font-bodoni-moda)"],
        "label-sm": ["var(--font-hanken-grotesk)"],
        "body-md": ["var(--font-hanken-grotesk)"],
        "display-lg": ["var(--font-bodoni-moda)"],
        "headline-lg": ["var(--font-bodoni-moda)"],
        "body-lg": ["var(--font-hanken-grotesk)"],
        "data-display": ["var(--font-hanken-grotesk)"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "data-display": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
